version: '3.8'

services:
  commander-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CommanderConnection=Server=192.168.29.138;Database=commanderDB;User Id=CommanderAPI;Password=asd@123;
    deploy:
      replicas: 3
    ports:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - commander-app
